
server:
  port: 9080
  servlet:
    context-path: /payments

spring:
  jpa:
    hibernate:
      ddl-auto: none


#Actuator Configuration

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

info:
  app:
    name: ${name}
    version: ${version}
    description: ${description}